Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkShop1.Models;
using WorkShop1.ViewModels;

namespace WorkShop1.Controllers
{
    public class CoursesController : Controller
    {
        private readonly WorkShop1Context _context;

        public CoursesController(WorkShop1Context context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index(int courseSemester, string searchString, string courseProgramme)
        {
            IQueryable<Course> courses = _context.Course.AsQueryable();
            IQueryable<int> semesterQuery = (IQueryable<int>)_context.Course.OrderBy(m => m.Semester).Select(m => m.Semester).Distinct();
            IQueryable<string> programmeQuery = (IQueryable<string>)_context.Course.OrderBy(m => m.Programme).Select(m => m.Programme).Distinct();

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.Title.Contains(searchString));
            }
            if (courseSemester != 0)
            {
                courses = courses.Where(x => x.Semester == courseSemester);
            }

            if (!string.IsNullOrEmpty(courseProgramme))
            {
                courses = courses.Where(x => x.Programme == courseProgramme);
            }

            courses = courses.Include(m => m.FirstTeacher).Include(m => m.SecondTeacher);

            var courseSemesterVM = new CourseSemesterViewModel
            {
                Semesters = new SelectList(await semesterQuery.ToListAsync()),
                Programmes=new SelectList(await programmeQuery.ToListAsync()),
                Courses = await courses.ToListAsync()
            };

            return View(courseSemesterVM);
            //var workShop1Context = _context.Course.Include(c => c.FirstTeacher).Include(c => c.SecondTeacher);
            //return View(await workShop1Context.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["FirstTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName");
            ViewData["SecondTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Set<Teacher>(), "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }
    }
}

Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkShop1.Models;
using WorkShop1.ViewModels;

namespace WorkShop1.Controllers
{
    public class TeachersController : Controller
    {
        private readonly WorkShop1Context _context;

        public TeachersController(WorkShop1Context context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index(string teacherFullName, string teacherDegree, string teacherAcademicRank)
        {
            IQueryable<Teacher> teachers = _context.Teacher.AsQueryable();
            IQueryable<string> fullNameQuery = (IQueryable<string>)_context.Teacher.OrderBy(m => m.FullName).Select(m => m.FullName).Distinct();
            IQueryable<string> degreeQuery = (IQueryable<string>)_context.Teacher.OrderBy(m => m.Degree).Select(m => m.Degree).Distinct();
            IQueryable<string> academicRankQuery = (IQueryable<string>)_context.Teacher.OrderBy(m => m.AcademicRank).Select(m => m.AcademicRank).Distinct();

            if (!string.IsNullOrEmpty(teacherFullName))
            {
                teachers = teachers.Where(s => s.FullName.Contains(teacherFullName));
            }

            if (!string.IsNullOrEmpty(teacherDegree))
            {
                teachers = teachers.Where(s => s.Degree.Contains(teacherDegree));
            }

            if (!string.IsNullOrEmpty(teacherAcademicRank))
            {
                teachers = teachers.Where(s => s.AcademicRank.Contains(teacherAcademicRank));
            }

            //teachers = teachers.Include(m => m.FirstTeacher).Include(m => m.SecondTeacher);

            var teacherDegreeVM = new TeacherDegreeViewModel
            {
                Degrees = new SelectList(await degreeQuery.ToListAsync()),
                AcademicRanks = new SelectList(await academicRankQuery.ToListAsync()),
                Teachers = await teachers.ToListAsync()
            };

            return View(teacherDegreeVM);
            //var workShop1Context = _context.Course.Include(c => c.FirstTeacher).Include(c => c.SecondTeacher);
            //return View(await workShop1Context.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }
    }
}

Views/Courses/Create.cshtml
@model WorkShop1.Models.Course

@{
    ViewData["Title"] = "Креирај предмет";
}

<h2>Креирај</h2>

<h4>Предмет</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programme" class="control-label"></label>
                <input asp-for="Programme" class="form-control" />
                <span asp-validation-for="Programme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EducationLevel" class="control-label"></label>
                <input asp-for="EducationLevel" class="form-control" />
                <span asp-validation-for="EducationLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstTeacherId" class="control-label">Професор</label>
                <select asp-for="FirstTeacherId" class ="form-control" asp-items="ViewBag.FirstTeacherId">
                    <option value="">Селектирај</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SecondTeacherId" class="control-label">Асистент</label>
                <select asp-for="SecondTeacherId" class="form-control" asp-items="ViewBag.SecondTeacherId">
                    <option value="">Селектирај</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Креирај" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад кон листата</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Courses/Delete.cshtml
@model WorkShop1.Models.Course

@{
    ViewData["Title"] = "Избриши предмет";
}

<h2>Избриши</h2>

<h3>Дали сте сигурни дека сакате да го избришете предметот?</h3>
<div>
    <h4>Предмет</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstTeacher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstTeacher.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondTeacher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondTeacher.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Избриши" class="btn btn-default" /> |
        <a asp-action="Index">Назад кон листата</a>
    </form>
</div>

Views/Courses/Details.cshtml
@model WorkShop1.Models.Course

@{
    ViewData["Title"] = "Повеќе информации за предметот";
}

<h2>Повеќе информации</h2>

<div>
    <h4>Предмет</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstTeacher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstTeacher.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondTeacher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondTeacher.FullName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Измени</a> |
    <a asp-action="Index">Назад кон листата</a>
</div>

Views/Courses/Edit.cshtml
@model WorkShop1.Models.Course

@{
    ViewData["Title"] = "Измени предмет";
}

<h2>Измени</h2>

<h4>Предмет</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programme" class="control-label"></label>
                <input asp-for="Programme" class="form-control" />
                <span asp-validation-for="Programme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EducationLevel" class="control-label"></label>
                <input asp-for="EducationLevel" class="form-control" />
                <span asp-validation-for="EducationLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstTeacherId" class="control-label"></label>
                <select asp-for="FirstTeacherId" class="form-control" asp-items="ViewBag.FirstTeacherId">
                    <option value="">Селектирај</option>
                </select>
                <span asp-validation-for="FirstTeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondTeacherId" class="control-label"></label>
                <select asp-for="SecondTeacherId" class="form-control" asp-items="ViewBag.SecondTeacherId">
                    <option value="">Селектирај</option>
                </select>
                <span asp-validation-for="SecondTeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад кон листата</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#SelectedTeachers").select2();
        });
    </script>
}

Views/Courses/Index.cshtml
@model WorkShop1.ViewModels.CourseSemesterViewModel

@{
    ViewData["Title"] = "Листа на предмети";
}

<h2>Предмети</h2>

<p>
    <a asp-action="Create">Креирај нов предмет</a>
</p>

<form asp-controller="Courses" asp-action="Index" method="get">
    <p>
        Име: <input type="text" asp-for="SearchString"/>

        Семестар: <select asp-for="CourseSemester" asp-items="Model.Semesters">
            <option value="">Сите</option>
        </select>

        Смер: <select asp-for="CourseProgramme" asp-items="Model.Programmes">
            <option value="">Сите</option>
        </select>
        <input type="submit" value="Филтрирај" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Credits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Programme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].EducationLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].FirstTeacher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].SecondTeacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Courses)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Credits)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Semester)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Programme)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EducationLevel)
                </td>
                <td>
                    @if (item.FirstTeacherId != null)
                    {
                        <a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.FirstTeacherId">@Html.DisplayFor(modelItem => item.FirstTeacher.FullName)</a>
                    }
                </td>
                <td>
                    @if (item.SecondTeacherId != null)
                    {
                        <a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.SecondTeacherId">@Html.DisplayFor(modelItem => item.SecondTeacher.FullName)</a>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Измени</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Детали</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Избриши</a>
                </td>
            </tr>
        }
    </tbody>
</table>